= Getting Started with Commodore Components

This tutorial provides all the information required to create your first Commodore component. https://syn.tools/tuto/index.html[This tutorial can be found] in the official Project Syn documentation.

== Contents

The contents of the tutorial are in the `docs/modules/ROOT/pages/index.adoc` file. The scripts help encapsulate the knowledge required to spin up a Project Syn installation with at least 2 clusters.

The instructions of the tutorial guide the user to the creation and deployment of a simple component.

== Requirements

The `0_requirements.sh` script shows the current versions of all required software.

=== Podman instead of Docker

If you do not have Docker installed or would prefer to use https://podman.io/[Podman], https://kind.sigs.k8s.io/[kind] is 100% compatible with Podman and has been successfully tested with this tutorial.

At the time of the last update of this document, k3d 5.5 is not compatible with Podman, https://k3d.io/v5.5.1/usage/advanced/podman/[despite what the documentation says].

== Build PDF

Use the `make pdf` command to create a PDF file out of the source Asciidoc file in the `build` folder. This operation requires Docker.

== Troubleshooting

Some users of Btrfs-on-LUKS have experimented issues with the tutorial. You might want to perform the following changes in that case.

. In `1_lieutenant_on_minikube.sh`, line 12, use the following command to start Minikube: `minikube start --disk-size 60g --cpus 4 --feature-gates="LocalStorageCapacityIsolation=false"`
. In `4_synthesize_on_k3s.sh`, replace line 22 `k3d cluster create projectsyn` with the following:

[source,bash]
--
if [ -d /dev/mapper ]; then
k3d_extra_args="-v /dev/mapper:/dev/mapper"
else
k3d_extra_args=""
fi
k3d cluster create projectsyn ${k3d_extra_args}
--
